import {
  Hackathon,
  Participant,
  Team,
  Submission,
  Judge,
  Evaluation,
} from '@/types';

export const MOCK_HACKATHONS: Hackathon[] = [
  {
    id: 'hack-001',
    slug: 'quantum-build-2026',
    title: 'QUANTUM BUILD 2026',
    tagline: 'AI • CIVIL TECH • ROBOTICS',
    organization: 'Zapsters Labs',
    organizationLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
    status: 'LIVE',
    startDate: '12 September 2026',
    endDate: '14 September 2026',
    durationHours: 48,
    location: 'Chennai / Online',
    isOnline: true,
    prizePool: '₹5,00,000',
    participantsCount: 842,
    teamsCount: 186,
    activeTeamsCount: 141,
    submissionRate: 87,
    judgingRate: 63,
    tracks: [
      {
        id: 'tr-1',
        name: '01 AI Infrastructure',
        description: 'High-throughput LLM runtime optimization, real-time observability, and distributed inference engines.',
        prize: '₹2,00,000',
      },
      {
        id: 'tr-2',
        name: '02 Computer Vision',
        description: 'Edge video analytics, spatial computing models, and industrial inspection automation.',
        prize: '₹1,50,000',
      },
      {
        id: 'tr-3',
        name: '03 Robotics & Civil Tech',
        description: 'Autonomous drone fleet pathfinding, urban infrastructure sensors, and disaster recovery tech.',
        prize: '₹1,50,000',
      },
    ],
    timeline: [
      { id: 't1', name: 'Registration', date: 'AUG 01 - SEP 10', status: 'COMPLETED' },
      { id: 't2', name: 'Team Formation', date: 'SEP 11', status: 'COMPLETED' },
      { id: 't3', name: 'Hacking Phase', date: 'SEP 12 (09:00 IST)', status: 'IN_PROGRESS' },
      { id: 't4', name: 'Project Submission', date: 'SEP 14 (09:00 IST)', status: 'UPCOMING' },
      { id: 't5', name: 'Judging Phase', date: 'SEP 14 (10:00 IST)', status: 'UPCOMING' },
      { id: 't6', name: 'Grand Finals', date: 'SEP 14 (17:00 IST)', status: 'UPCOMING' },
    ],
    prizes: [
      { title: 'Grand Winner', amount: '₹2,00,000', description: 'Overall highest score across all tracks + Cloud credits' },
      { title: 'First Runner Up', amount: '₹1,00,000', description: 'Second place overall + Mentorship access' },
      { title: 'Second Runner Up', amount: '₹50,000', description: 'Third place overall' },
      { title: 'Best Hardware / Edge Integration', amount: '₹75,000', description: 'Awarded to the top edge compute or robotics project' },
      { title: 'Community Choice', amount: '₹75,000', description: 'Voted by hackathon participants' },
    ],
    rules: [
      'Teams must consist of 2 to 4 eligible registered hackers.',
      'All code submitted must be written during the 48-hour hacking window.',
      'Pre-existing open-source packages and frameworks are allowed, but core intellectual property must be original.',
      'GitHub repository commits will be audited by the automated Zapsters Activity Engine.',
      'Submissions must include a working repository, video demo (max 3 minutes), and architecture slide deck.',
    ],
    sponsors: [
      { id: 'sp-1', name: 'NVIDIA AI', tier: 'Title', logo: 'NVIDIA' },
      { id: 'sp-2', name: 'Vercel Foundation', tier: 'Platinum', logo: 'VERCEL' },
      { id: 'sp-3', name: 'Supabase Data Labs', tier: 'Gold', logo: 'SUPABASE' },
      { id: 'sp-4', name: 'Postman Labs', tier: 'Track', logo: 'POSTMAN' },
    ],
    faqs: [
      { question: 'Who can participate in Quantum Build 2026?', answer: 'Developers, researchers, hardware engineers, and designers worldwide are welcome.' },
      { question: 'How is code activity verified?', answer: 'Zapsters inspects GitHub webhooks for commit frequency, PR velocity, and code contribution balance across team members.' },
      { question: 'What is the format of the final pitch?', answer: 'Top 5 teams from judging will present a live 5-minute pitch to the executive jury.' },
    ],
    description: 'Quantum Build 2026 is the premier 48-hour hardware and AI engineering hackathon designed to push the boundaries of real-time infrastructure, vision models, and civil robotics.',
  },
  {
    id: 'hack-002',
    slug: 'cyberforge-summit',
    title: 'CYBERFORGE SUMMIT 2026',
    tagline: 'ZERO TRUST • CRYPTO • THREAT INTEL',
    organization: 'CyberForge Alliance',
    status: 'UPCOMING',
    startDate: '04 October 2026',
    endDate: '06 October 2026',
    durationHours: 36,
    location: 'Bengaluru / Hybrid',
    isOnline: false,
    prizePool: '$25,000',
    participantsCount: 520,
    teamsCount: 112,
    activeTeamsCount: 0,
    submissionRate: 0,
    judgingRate: 0,
    tracks: [
      { id: 'tr-c1', name: 'Zero Trust Architecture', description: 'Granular policy engines and cryptographic access layers.', prize: '$10,000' },
      { id: 'tr-c2', name: 'Automated Red Teaming', description: 'AI agents simulating zero-day exploit execution.', prize: '$10,000' },
    ],
    timeline: [],
    prizes: [],
    rules: [],
    sponsors: [],
    faqs: [],
    description: 'Intense offensive and defensive cybersecurity hacking competition focusing on zero-trust protocol primitives.',
  },
  {
    id: 'hack-003',
    slug: 'neural-matrix-2026',
    title: 'NEURAL MATRIX',
    tagline: 'AUTONOMOUS AGENTS • RAG ENGINES',
    organization: 'OpenAI Ecosystem',
    status: 'JUDGING',
    startDate: '01 August 2026',
    endDate: '03 August 2026',
    durationHours: 48,
    location: 'Online',
    isOnline: true,
    prizePool: '$50,000',
    participantsCount: 1420,
    teamsCount: 310,
    activeTeamsCount: 290,
    submissionRate: 94,
    judgingRate: 82,
    tracks: [],
    timeline: [],
    prizes: [],
    rules: [],
    sponsors: [],
    faqs: [],
    description: 'Global benchmark competition for autonomous multi-agent systems and real-time structured knowledge synthesis.',
  },
];

export const MOCK_PARTICIPANT: Participant = {
  id: 'usr-001',
  username: 'rahul_dev',
  name: 'Rahul Sharma',
  title: 'AI / ML · Full Stack · Computer Vision',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  bio: 'Building autonomous computer vision pipelines and distributed real-time AI systems. Veteran of 8 hackathons, passionate about high-performance edge compute.',
  roles: ['AI/ML Engineer', 'Full Stack Developer', 'Team Lead'],
  skills: ['Python', 'PyTorch', 'TypeScript', 'Next.js', 'FastAPI', 'OpenCV', 'CUDA', 'Docker'],
  githubHandle: 'rahul-ai-dev',
  linkedinUrl: 'https://linkedin.com/in/rahulsharma-ai',
  stats: {
    hackathonsCount: 8,
    wins: 2,
    finals: 4,
    projectsCount: 17,
  },
  projects: [
    {
      name: 'Sentinel',
      description: 'AI-powered industrial threat detection platform with edge vision models.',
      hackathonName: 'QUANTUM BUILD 2026',
      year: '2026',
    },
    {
      name: 'Project Alpha',
      description: 'AI infrastructure monitoring & dynamic telemetry aggregation.',
      hackathonName: 'NEURAL MATRIX 2026',
      year: '2026',
    },
    {
      name: 'Project Beta',
      description: 'Computer vision inspection pipeline for high-speed manufacturing lines.',
      hackathonName: 'HACKX 2025',
      year: '2025',
    },
    {
      name: 'Aether OS',
      description: 'Zero-latency edge agent orchestrator written in Rust.',
      hackathonName: 'DEVFORGE 2025',
      year: '2025',
    },
  ],
  competitionHistory: [
    { id: 'ch-1', hackathonName: 'QUANTUM BUILD 2026', year: '2026', result: 'Winner', badge: 'Winner', score: 94.2 },
    { id: 'ch-2', hackathonName: 'HackX National', year: '2025', result: 'Finalist', badge: 'Finalist', score: 88.1 },
    { id: 'ch-3', hackathonName: 'DevForge 2025', year: '2025', result: '1st Place (AI Track)', badge: 'Winner', score: 92.6 },
    { id: 'ch-4', hackathonName: 'Global AI Hackathon', year: '2024', result: 'Top 10 Finalist', badge: 'Top 10', score: 85.0 },
  ],
};

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-001',
    slug: 'neural-forge',
    name: 'Neural Forge',
    rank: 1,
    score: 94.2,
    hackathonId: 'hack-001',
    hackathonTitle: 'QUANTUM BUILD 2026',
    track: '01 AI Infrastructure',
    status: 'ACTIVE',
    activityLevel: 'HIGH',
    scoreTrend: '+2.1',
    members: [
      { id: 'm1', name: 'Sarah Chen', username: 'sarah_c', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80', role: 'AI Lead', contributionPercentage: 35 },
      { id: 'm2', name: 'Marcus Vance', username: 'mvance', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80', role: 'Systems Architect', contributionPercentage: 28 },
      { id: 'm3', name: 'Elena Rostova', username: 'elena_r', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80', role: 'Frontend Lead', contributionPercentage: 22 },
      { id: 'm4', name: 'David Kim', username: 'dkim', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80', role: 'DevOps / Infra', contributionPercentage: 15 },
    ],
    project: {
      id: 'proj-001',
      name: 'OmniInference Engine',
      tagline: 'Sub-millisecond distributed LLM streaming engine with speculative token execution.',
      description: 'OmniInference bypasses traditional cloud bottlenecks by utilizing edge p2p GPU clustering and custom TensorRT-LLM Kernels, enabling real-time voice and vision agent execution.',
      repoUrl: 'https://github.com/neuralforge/omni-inference',
      demoUrl: 'https://omni-inference-demo.zapsters.dev',
      presentationUrl: 'https://slides.com/neuralforge/omni-deck',
      techStack: ['Rust', 'CUDA', 'PyTorch', 'Next.js', 'gRPC', 'WebRTC'],
      screenshots: ['/images/project1.png'],
      commitsCount: 184,
      prsCount: 42,
      issuesCount: 26,
      tasksCount: 89,
      activeDays: 14,
    },
    tasks: [
      { id: 'tk-1', title: 'Implement custom CUDA kernel for INT4 quantization', assignee: 'Sarah Chen', status: 'DONE' },
      { id: 'tk-2', title: 'Setup WebRTC audio stream bridge', assignee: 'Elena Rostova', status: 'DONE' },
      { id: 'tk-3', title: 'P2P node discovery protocol', assignee: 'Marcus Vance', status: 'IN_PROGRESS' },
    ],
    contributionSplit: [
      { name: 'Sarah Chen', percentage: 35 },
      { name: 'Marcus Vance', percentage: 28 },
      { name: 'Elena Rostova', percentage: 22 },
      { name: 'David Kim', percentage: 15 },
    ],
    activityLog: [
      { id: 'act-1', timestamp: '11:42', author: 'Sarah Chen', action: 'opened PR #54', detail: 'Optimize INT8 matrix multiplication kernel', type: 'pr' },
      { id: 'act-2', timestamp: '11:15', author: 'Marcus Vance', action: 'closed issue #31', detail: 'Fix gRPC payload buffer alignment', type: 'issue' },
      { id: 'act-3', timestamp: '10:48', author: 'Elena Rostova', action: 'pushed 6 commits', detail: 'Add live latency spectrum graph to dashboard', type: 'commit' },
      { id: 'act-4', timestamp: '10:02', author: 'David Kim', action: 'completed TASK-41', detail: 'Deploy edge node staging cluster on AWS', type: 'task' },
    ],
  },
  {
    id: 'team-002',
    slug: 'codex-labs',
    name: 'CodeX',
    rank: 2,
    score: 91.8,
    hackathonId: 'hack-001',
    hackathonTitle: 'QUANTUM BUILD 2026',
    track: '01 AI Infrastructure',
    status: 'ACTIVE',
    activityLevel: 'HIGH',
    scoreTrend: '+0.8',
    members: [
      { id: 'm5', name: 'Alex Rivera', username: 'arivera', avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80', role: 'Full Stack', contributionPercentage: 40 },
      { id: 'm6', name: 'Priya Sharma', username: 'psharma', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80', role: 'ML Engineer', contributionPercentage: 35 },
      { id: 'm7', name: 'Kenji Sato', username: 'ksato', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80', role: 'Backend', contributionPercentage: 25 },
    ],
    project: {
      id: 'proj-002',
      name: 'GridLens AI',
      tagline: 'Autonomous power grid telemetry analysis with anomaly forecasting.',
      description: 'GridLens analyzes millions of IoT sensor signals per second to prevent power surges and predict transformer failures.',
      repoUrl: 'https://github.com/codex-labs/gridlens',
      demoUrl: 'https://gridlens.zapsters.dev',
      presentationUrl: 'https://slides.com/codex/gridlens',
      techStack: ['Python', 'FastAPI', 'Apache Kafka', 'React', 'TimescaleDB'],
      screenshots: [],
      commitsCount: 156,
      prsCount: 34,
      issuesCount: 19,
      tasksCount: 72,
      activeDays: 12,
    },
    tasks: [],
    contributionSplit: [
      { name: 'Alex Rivera', percentage: 40 },
      { name: 'Priya Sharma', percentage: 35 },
      { name: 'Kenji Sato', percentage: 25 },
    ],
    activityLog: [],
  },
  {
    id: 'team-003',
    slug: 'cyberforge',
    name: 'CyberForge',
    rank: 3,
    score: 87.4,
    hackathonId: 'hack-001',
    hackathonTitle: 'QUANTUM BUILD 2026',
    track: '02 Computer Vision',
    status: 'ACTIVE',
    activityLevel: 'HIGH',
    scoreTrend: '—',
    members: [
      { id: 'm8', name: 'Rahul Sharma', username: 'rahul_dev', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80', role: 'AI / ML Lead', contributionPercentage: 34 },
      { id: 'm9', name: 'Arun Kumar', username: 'arunk', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80', role: 'Backend Engineer', contributionPercentage: 27 },
      { id: 'm10', name: 'Vishnu Vardhan', username: 'vishnu_v', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80', role: 'Frontend Architect', contributionPercentage: 23 },
      { id: 'm11', name: 'Adithya Nair', username: 'adithya_n', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80', role: 'Security & QA', contributionPercentage: 16 },
    ],
    project: {
      id: 'proj-003',
      name: 'Sentinel Vision',
      tagline: 'AI-powered zero-trust industrial threat detection and vision safety platform.',
      description: 'Sentinel continuously monitors factory floor cameras using spatial YOLOv9 models to detect safety hazards, perimeter breaches, and structural anomalies in sub-10ms intervals.',
      repoUrl: 'https://github.com/cyberforge/sentinel',
      demoUrl: 'https://sentinel-cyberforge.zapsters.dev',
      presentationUrl: 'https://slides.com/cyberforge/sentinel-pitch',
      techStack: ['Python', 'YOLOv9', 'FastAPI', 'React', 'OpenCV', 'TensorRT', 'TailwindCSS'],
      screenshots: [],
      commitsCount: 142,
      prsCount: 31,
      issuesCount: 18,
      tasksCount: 67,
      activeDays: 9,
    },
    tasks: [
      { id: 't-s1', title: 'Integrate OpenCV camera stream buffer', assignee: 'Rahul Sharma', status: 'DONE' },
      { id: 't-s2', title: 'Build spatial overlay canvas on React frontend', assignee: 'Vishnu Vardhan', status: 'DONE' },
      { id: 't-s3', title: 'Implement WebSocket alert pipeline', assignee: 'Arun Kumar', status: 'DONE' },
      { id: 't-s4', title: 'Audit model payload authorization middleware', assignee: 'Adithya Nair', status: 'IN_PROGRESS' },
    ],
    contributionSplit: [
      { name: 'Rahul Sharma', percentage: 34 },
      { name: 'Arun Kumar', percentage: 27 },
      { name: 'Vishnu Vardhan', percentage: 23 },
      { name: 'Adithya Nair', percentage: 16 },
    ],
    activityLog: [
      { id: 'act-cf1', timestamp: '11:42', author: 'Rahul Sharma', action: 'opened PR #42', detail: 'Optimize spatial bounding box calculations', type: 'pr' },
      { id: 'act-cf2', timestamp: '10:18', author: 'Arun Kumar', action: 'closed issue #18', detail: 'Fix memory leak in camera feed buffer', type: 'issue' },
      { id: 'act-cf3', timestamp: '09:57', author: 'Vishnu Vardhan', action: 'pushed 4 commits', detail: 'Update dashboard telemetry component', type: 'commit' },
      { id: 'act-cf4', timestamp: '09:21', author: 'Adithya Nair', action: 'completed TASK-28', detail: 'JWT auth verification on stream route', type: 'task' },
      { id: 'act-cf5', timestamp: '08:42', author: 'Rahul Sharma', action: 'merged PR #41', detail: 'TensorRT model loading pipeline', type: 'merge' },
    ],
  },
  {
    id: 'team-004',
    slug: 'byte-builders',
    name: 'ByteBuilders',
    rank: 4,
    score: 84.7,
    hackathonId: 'hack-001',
    hackathonTitle: 'QUANTUM BUILD 2026',
    track: '03 Robotics & Civil Tech',
    status: 'SUBMITTED',
    activityLevel: 'MEDIUM',
    scoreTrend: '-1.4',
    members: [
      { id: 'm12', name: 'Rohan Gupta', username: 'rohang', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80', role: 'Robotics Eng', contributionPercentage: 50 },
      { id: 'm13', name: 'Sneha Patel', username: 'spatel', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80', role: 'Embedded Systems', contributionPercentage: 50 },
    ],
    project: {
      id: 'proj-004',
      name: 'AeroPath Drone Fleet',
      tagline: 'Autonomous drone pathfinding for post-disaster flood mapping.',
      description: 'AeroPath uses mesh sensor arrays on micro-drones to construct top-down thermal damage heatmaps in real time.',
      repoUrl: 'https://github.com/bytebuilders/aeropath',
      demoUrl: 'https://aeropath.zapsters.dev',
      presentationUrl: '',
      techStack: ['C++', 'ROS2', 'Python', 'Mapbox', 'React'],
      screenshots: [],
      commitsCount: 98,
      prsCount: 19,
      issuesCount: 14,
      tasksCount: 45,
      activeDays: 8,
    },
    tasks: [],
    contributionSplit: [
      { name: 'Rohan Gupta', percentage: 50 },
      { name: 'Sneha Patel', percentage: 50 },
    ],
    activityLog: [],
  },
  {
    id: 'team-005',
    slug: 'null-pointer',
    name: 'Null Pointer',
    rank: 5,
    score: 81.3,
    hackathonId: 'hack-001',
    hackathonTitle: 'QUANTUM BUILD 2026',
    track: '03 Robotics & Civil Tech',
    status: 'AT_RISK',
    activityLevel: 'LOW',
    scoreTrend: '+3.2',
    members: [
      { id: 'm14', name: 'Vikram Seth', username: 'vseth', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80', role: 'Full Stack', contributionPercentage: 70 },
      { id: 'm15', name: 'Tanya Roy', username: 'troy', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80', role: 'Designer', contributionPercentage: 30 },
    ],
    project: {
      id: 'proj-005',
      name: 'CivicPulse',
      tagline: 'Crowdsourced urban infrastructure repair routing engine.',
      description: 'CivicPulse aggregates municipal reports and priorities repair routes for municipal crews.',
      repoUrl: 'https://github.com/nullpointer/civicpulse',
      demoUrl: '',
      presentationUrl: '',
      techStack: ['TypeScript', 'Next.js', 'PostgreSQL'],
      screenshots: [],
      commitsCount: 44,
      prsCount: 8,
      issuesCount: 5,
      tasksCount: 20,
      activeDays: 4,
    },
    tasks: [],
    contributionSplit: [
      { name: 'Vikram Seth', percentage: 70 },
      { name: 'Tanya Roy', percentage: 30 },
    ],
    activityLog: [],
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    teamId: 'team-001',
    teamName: 'Neural Forge',
    teamSlug: 'neural-forge',
    hackathonId: 'hack-001',
    track: '01 AI Infrastructure',
    projectName: 'OmniInference Engine',
    tagline: 'Sub-millisecond distributed LLM streaming engine.',
    description: 'OmniInference bypasses traditional cloud bottlenecks by utilizing edge p2p GPU clustering and custom TensorRT-LLM Kernels.',
    repoUrl: 'https://github.com/neuralforge/omni-inference',
    demoUrl: 'https://omni-inference-demo.zapsters.dev',
    presentationUrl: 'https://slides.com/neuralforge/omni-deck',
    techStack: ['Rust', 'CUDA', 'PyTorch', 'Next.js'],
    submittedAt: '13 Sep 2026, 22:15 IST',
    status: 'EVALUATED',
    evaluationCount: 4,
    averageScore: 94.2,
  },
  {
    id: 'sub-002',
    teamId: 'team-002',
    teamName: 'CodeX',
    teamSlug: 'codex-labs',
    hackathonId: 'hack-001',
    track: '01 AI Infrastructure',
    projectName: 'GridLens AI',
    tagline: 'Autonomous power grid telemetry analysis.',
    description: 'GridLens analyzes millions of IoT sensor signals per second to prevent power surges.',
    repoUrl: 'https://github.com/codex-labs/gridlens',
    demoUrl: 'https://gridlens.zapsters.dev',
    presentationUrl: 'https://slides.com/codex/gridlens',
    techStack: ['Python', 'FastAPI', 'Apache Kafka'],
    submittedAt: '13 Sep 2026, 23:40 IST',
    status: 'EVALUATED',
    evaluationCount: 3,
    averageScore: 91.8,
  },
  {
    id: 'sub-003',
    teamId: 'team-003',
    teamName: 'CyberForge',
    teamSlug: 'cyberforge',
    hackathonId: 'hack-001',
    track: '02 Computer Vision',
    projectName: 'Sentinel Vision',
    tagline: 'AI-powered zero-trust industrial threat detection.',
    description: 'Sentinel continuously monitors factory floor cameras using spatial YOLOv9 models to detect safety hazards.',
    repoUrl: 'https://github.com/cyberforge/sentinel',
    demoUrl: 'https://sentinel-cyberforge.zapsters.dev',
    presentationUrl: 'https://slides.com/cyberforge/sentinel-pitch',
    techStack: ['Python', 'YOLOv9', 'FastAPI', 'React', 'OpenCV'],
    submittedAt: '14 Sep 2026, 01:10 IST',
    status: 'UNDER_REVIEW',
    evaluationCount: 2,
    averageScore: 87.4,
  },
  {
    id: 'sub-004',
    teamId: 'team-004',
    teamName: 'ByteBuilders',
    teamSlug: 'byte-builders',
    hackathonId: 'hack-001',
    track: '03 Robotics & Civil Tech',
    projectName: 'AeroPath Drone Fleet',
    tagline: 'Autonomous drone pathfinding for disaster mapping.',
    description: 'AeroPath uses mesh sensor arrays on micro-drones to construct thermal damage heatmaps.',
    repoUrl: 'https://github.com/bytebuilders/aeropath',
    demoUrl: 'https://aeropath.zapsters.dev',
    presentationUrl: '',
    techStack: ['C++', 'ROS2', 'Python'],
    submittedAt: '14 Sep 2026, 02:45 IST',
    status: 'SUBMITTED',
    evaluationCount: 1,
    averageScore: 84.7,
  },
];

export const MOCK_JUDGES: Judge[] = [
  {
    id: 'jdg-001',
    name: 'Dr. Aris Thorne',
    email: 'aris.thorne@nvidia.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    organization: 'NVIDIA AI Research',
    role: 'Principal CUDA Architect',
    assignedTeamsCount: 18,
    completedCount: 12,
    remainingCount: 6,
  },
  {
    id: 'jdg-002',
    name: 'Maya Lin',
    email: 'maya@vercel.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    organization: 'Vercel Engineering',
    role: 'Head of Infrastructure',
    assignedTeamsCount: 15,
    completedCount: 15,
    remainingCount: 0,
  },
  {
    id: 'jdg-003',
    name: 'Vikramaditya Roy',
    email: 'roy@quantum.org',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    organization: 'Zapsters Labs',
    role: 'VP of Robotics',
    assignedTeamsCount: 16,
    completedCount: 8,
    remainingCount: 8,
  },
];

export const MOCK_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval-001',
    judgeId: 'jdg-001',
    judgeName: 'Dr. Aris Thorne',
    teamId: 'team-003',
    teamName: 'CyberForge',
    hackathonId: 'hack-001',
    scores: {
      innovation: 27,   // Out of 30
      technical: 26,    // Out of 30
      impact: 17,       // Out of 20
      ux: 9,            // Out of 10
      presentation: 9,  // Out of 10
    },
    totalScore: 88,
    notes: 'Exceptional computer vision implementation using YOLOv9 custom TensorRT quantization. The WebSocket live overlay canvas operates smoothly under heavy camera stream load. Would like to see hardware benchmark results on Jetson Orin modules.',
    status: 'SAVED',
    updatedAt: '14 Sep 2026, 04:30 IST',
  },
];
