"""initial schema

Revision ID: 1f57d00e5c9e
Revises:
Create Date: 2026-08-14 09:16:08.202053

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1f57d00e5c9e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("logo", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=4000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_pkey")),
    )
    op.create_index(op.f("organization_slug_idx"), "organization", ["slug"], unique=True)
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("bio", sa.String(length=2000), nullable=True),
        sa.Column("avatar", sa.String(length=512), nullable=True),
        sa.Column("github_handle", sa.String(length=128), nullable=True),
        sa.Column("linkedin_url", sa.String(length=512), nullable=True),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("user_email_idx"), "user", ["email"], unique=True)
    op.create_index(op.f("user_username_idx"), "user", ["username"], unique=True)
    op.create_table(
        "hackathon",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("tagline", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=8000), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_hours", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("prize_pool", sa.String(length=128), nullable=True),
        sa.Column("participants_count", sa.Integer(), nullable=False),
        sa.Column("teams_count", sa.Integer(), nullable=False),
        sa.Column("submission_rate", sa.Integer(), nullable=False),
        sa.Column("judging_rate", sa.Integer(), nullable=False),
        sa.Column("active_teams_count", sa.Integer(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("faqs", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], name=op.f("hackathon_organization_id_fkey")),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name=op.f("hackathon_owner_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("hackathon_pkey")),
    )
    op.create_index(op.f("hackathon_slug_idx"), "hackathon", ["slug"], unique=True)
    op.create_table(
        "notification",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("notification_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_pkey")),
    )
    op.create_index(op.f("notification_user_id_idx"), "notification", ["user_id"], unique=False)
    op.create_table(
        "announcement",
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body", sa.String(length=8000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name=op.f("announcement_created_by_fkey")),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("announcement_hackathon_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("announcement_pkey")),
    )
    op.create_index(op.f("announcement_hackathon_id_idx"), "announcement", ["hackathon_id"], unique=False)
    op.create_table(
        "judge",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("organization", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=128), nullable=True),
        sa.Column("avatar", sa.String(length=512), nullable=True),
        sa.Column("assigned_teams_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("remaining_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("judge_hackathon_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("judge_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("judge_pkey")),
    )
    op.create_index(op.f("judge_hackathon_id_idx"), "judge", ["hackathon_id"], unique=False)
    op.create_table(
        "prize",
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("amount", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("prize_hackathon_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("prize_pkey")),
    )
    op.create_index(op.f("prize_hackathon_id_idx"), "prize", ["hackathon_id"], unique=False)
    op.create_table(
        "registration",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("team_name", sa.String(length=128), nullable=True),
        sa.Column("track", sa.String(length=128), nullable=True),
        sa.Column("team_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("registration_hackathon_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("registration_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("registration_pkey")),
    )
    op.create_index(op.f("registration_hackathon_id_idx"), "registration", ["hackathon_id"], unique=False)
    op.create_index(op.f("registration_user_id_idx"), "registration", ["user_id"], unique=False)
    op.create_table(
        "sponsor",
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("logo", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("sponsor_hackathon_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("sponsor_pkey")),
    )
    op.create_index(op.f("sponsor_hackathon_id_idx"), "sponsor", ["hackathon_id"], unique=False)
    op.create_table(
        "team",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("track", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("activity_level", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("score_trend", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("team_hackathon_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("team_pkey")),
    )
    op.create_index(op.f("team_hackathon_id_idx"), "team", ["hackathon_id"], unique=False)
    op.create_index(op.f("team_slug_idx"), "team", ["slug"], unique=True)
    op.create_table(
        "timeline_phase",
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("date", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("timeline_phase_hackathon_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("timeline_phase_pkey")),
    )
    op.create_index(op.f("timeline_phase_hackathon_id_idx"), "timeline_phase", ["hackathon_id"], unique=False)
    op.create_table(
        "track",
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("prize", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("track_hackathon_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("track_pkey")),
    )
    op.create_index(op.f("track_hackathon_id_idx"), "track", ["hackathon_id"], unique=False)
    op.create_table(
        "activity_item",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=256), nullable=False),
        sa.Column("detail", sa.String(length=2000), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("activity_item_team_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_item_pkey")),
    )
    op.create_index(op.f("activity_item_team_id_idx"), "activity_item", ["team_id"], unique=False)
    op.create_table(
        "evaluation",
        sa.Column("judge_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("notes", sa.String(length=8000), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("evaluation_hackathon_id_fkey")),
        sa.ForeignKeyConstraint(["judge_id"], ["judge.id"], name=op.f("evaluation_judge_id_fkey")),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("evaluation_team_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("evaluation_pkey")),
    )
    op.create_index(op.f("evaluation_hackathon_id_idx"), "evaluation", ["hackathon_id"], unique=False)
    op.create_index(op.f("evaluation_judge_id_idx"), "evaluation", ["judge_id"], unique=False)
    op.create_index(op.f("evaluation_team_id_idx"), "evaluation", ["team_id"], unique=False)
    op.create_table(
        "project",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("tagline", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=8000), nullable=True),
        sa.Column("repo_url", sa.String(length=512), nullable=True),
        sa.Column("demo_url", sa.String(length=512), nullable=True),
        sa.Column("presentation_url", sa.String(length=512), nullable=True),
        sa.Column("tech_stack", sa.JSON(), nullable=False),
        sa.Column("screenshots", sa.JSON(), nullable=False),
        sa.Column("commits_count", sa.Integer(), nullable=False),
        sa.Column("prs_count", sa.Integer(), nullable=False),
        sa.Column("issues_count", sa.Integer(), nullable=False),
        sa.Column("tasks_count", sa.Integer(), nullable=False),
        sa.Column("active_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("project_team_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("project_pkey")),
    )
    op.create_index(op.f("project_team_id_idx"), "project", ["team_id"], unique=False)
    op.create_table(
        "submission",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("hackathon_id", sa.Uuid(), nullable=False),
        sa.Column("track", sa.String(length=128), nullable=True),
        sa.Column("project_name", sa.String(length=256), nullable=False),
        sa.Column("tagline", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=8000), nullable=True),
        sa.Column("repo_url", sa.String(length=512), nullable=True),
        sa.Column("demo_url", sa.String(length=512), nullable=True),
        sa.Column("presentation_url", sa.String(length=512), nullable=True),
        sa.Column("tech_stack", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evaluation_count", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathon.id"], name=op.f("submission_hackathon_id_fkey")),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("submission_team_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("submission_pkey")),
    )
    op.create_index(op.f("submission_hackathon_id_idx"), "submission", ["hackathon_id"], unique=False)
    op.create_index(op.f("submission_team_id_idx"), "submission", ["team_id"], unique=False)
    op.create_table(
        "team_member",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("contribution_percentage", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("team_member_team_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("team_member_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("team_member_pkey")),
    )
    op.create_index(op.f("team_member_team_id_idx"), "team_member", ["team_id"], unique=False)
    op.create_index(op.f("team_member_user_id_idx"), "team_member", ["user_id"], unique=False)
    op.create_table(
        "team_task",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["assignee_id"], ["user.id"], name=op.f("team_task_assignee_id_fkey")),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("team_task_team_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("team_task_pkey")),
    )
    op.create_index(op.f("team_task_team_id_idx"), "team_task", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("team_task_team_id_idx"), table_name="team_task")
    op.drop_table("team_task")
    op.drop_index(op.f("team_member_user_id_idx"), table_name="team_member")
    op.drop_index(op.f("team_member_team_id_idx"), table_name="team_member")
    op.drop_table("team_member")
    op.drop_index(op.f("submission_team_id_idx"), table_name="submission")
    op.drop_index(op.f("submission_hackathon_id_idx"), table_name="submission")
    op.drop_table("submission")
    op.drop_index(op.f("project_team_id_idx"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("evaluation_team_id_idx"), table_name="evaluation")
    op.drop_index(op.f("evaluation_judge_id_idx"), table_name="evaluation")
    op.drop_index(op.f("evaluation_hackathon_id_idx"), table_name="evaluation")
    op.drop_table("evaluation")
    op.drop_index(op.f("activity_item_team_id_idx"), table_name="activity_item")
    op.drop_table("activity_item")
    op.drop_index(op.f("track_hackathon_id_idx"), table_name="track")
    op.drop_table("track")
    op.drop_index(op.f("timeline_phase_hackathon_id_idx"), table_name="timeline_phase")
    op.drop_table("timeline_phase")
    op.drop_index(op.f("team_slug_idx"), table_name="team")
    op.drop_index(op.f("team_hackathon_id_idx"), table_name="team")
    op.drop_table("team")
    op.drop_index(op.f("sponsor_hackathon_id_idx"), table_name="sponsor")
    op.drop_table("sponsor")
    op.drop_index(op.f("registration_user_id_idx"), table_name="registration")
    op.drop_index(op.f("registration_hackathon_id_idx"), table_name="registration")
    op.drop_table("registration")
    op.drop_index(op.f("prize_hackathon_id_idx"), table_name="prize")
    op.drop_table("prize")
    op.drop_index(op.f("judge_hackathon_id_idx"), table_name="judge")
    op.drop_table("judge")
    op.drop_index(op.f("announcement_hackathon_id_idx"), table_name="announcement")
    op.drop_table("announcement")
    op.drop_index(op.f("notification_user_id_idx"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("hackathon_slug_idx"), table_name="hackathon")
    op.drop_table("hackathon")
    op.drop_index(op.f("user_username_idx"), table_name="user")
    op.drop_index(op.f("user_email_idx"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("organization_slug_idx"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
