"""add team invite code and hackathon rubric

Revision ID: bb83b45147c2
Revises: 1f57d00e5c9e
Create Date: 2026-08-14 14:38:06.238641

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bb83b45147c2"
down_revision: str | None = "1f57d00e5c9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hackathon", sa.Column("rubric", sa.JSON(), nullable=True))
    op.add_column("team", sa.Column("invite_code", sa.String(length=16), nullable=True))
    op.create_index(op.f("team_invite_code_idx"), "team", ["invite_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("team_invite_code_idx"), table_name="team")
    op.drop_column("team", "invite_code")
    op.drop_column("hackathon", "rubric")
    # ### end Alembic commands ###
